entities/user.go
entities/user_test.go
go.sum
routers/api/v1/router.go
routers/api/v1/router_test.go
routers/api/v1/teams_test.go
routers/api/v1/types.go
routers/api/v1/users.go
routers/api/v1/users_test.go
services/emailService.go
testutils/testDB.go
testutils/testutils.go
utils/auth/auth.go

Updated the `/api/v1/users/verify` endpoint to include the user's ID and auth level in the response. No changes to the request were made.

Extend Verify endpoint to include user's ID and auth level in response

---

routers/api/v1/teams.go
routers/api/v1/users.go
routers/frontend/routes.go

Reduces the log level used for logging user mistakes (invalid parameters for requests, unauthorized requests etc.) from Warn to Debug.
I wanted to standardize how we log information in the app and tried to enforce a pattern that I see being used quite frequently:
- Error level is used for problems that are degrading the user experience
- Warn level is used for problems that might cause a degrading effect on the user experience in the future
- Info level is used for logging one-time events, or at least when the number of times the event gets logged does not depend on the number of requests received (O(1) in terms of the number of requests received)
- Debug level is used for logging problems that do not degrade the user experience (e.g.: errors caused by invalid input) and any other …

Log user mistakes at Debug level

---

entities/user_test.go
routers/api/v1/router.go
routers/api/v1/router_test.go
routers/api/v1/users.go
routers/frontend/router.go
routers/frontend/routes.go
routers/frontend/routes_test.go
services/errors.go
services/userService.go
static/js/admin.js
utils/auth/auth_test.go
utils/auth/common/authLevel.go
utils/auth/common/authLevel_test.go

For issue #28 
Implements string based auth level for JSON responses. String auth levels are only used when sending a response in JSON, internally the app still uses ints as it is much safer to compare ints than strings.
Also renames the auth level `Organizer` to `Organiser` because we're not 'murican.

Implement string based auth levels for JSON responses

---

routers/frontend/router.go
routers/frontend/router_test.go
routers/frontend/routes.go
routers/frontend/routes_test.go
services/sendgrid/emailService.go
services/sendgrid/emailService_test.go
templates/emails/emailVerify_email.gohtml
templates/pages/emailNotVerified.gohtml
templates/pages/emailVerifyResend.gohtml
templates/pages/verificationTokenInvalid.gohtml
wire_gen.go

For issue #28 
Users are now able to get a new verification email. When a user with auth level `Unverified` logs in, they get redirected a page telling them that their email is unverified and provides a link to send a new verification email to their email address.
Implements:
- Verification resend functionality
- Page for users with auth level `Unverified` which provides a link to send a new verification email to their email address.
- Page for when users try to verify their email with an invalid token which provides information on how to get a new token

Email verify resend

---

templates/pages/profile.gohtml
templates/partials/teamPanel.gohtml

For issue #45 
Adds a small warning on the team panel on the profile page that teams of more than 4 people will not be able to compete for prizes.

Add warning of soft team member count limit

---

.dockerignore

Resolves issue #56 
Adds the mongo database `data` folder to docker ignore. Ensures docker doesn't attempt to bundle the folder during the build process

Add mongo data folder to dockerignore in prod

---

services/mongo/userService.go
services/mongo/userService_test.go

Resolves #59 
Email is now converted to lowercase during login or when registering a new account
Add test for checking email check is case insensitive

Email should be case-insensitive during login

---

templates/partials/teamPanel.gohtml

for issue #45
Edited the warning message so that if the member count limit is exceeded, the warning would become red, capitalized and bold.

Add dynamic warning for team member count limit

---

README.md

Noticed a small mistake in the README.
The correct command to start the app in development mode is `make up-dev` not `make up`

Fix dev env deployment instructions

---

routers/api/v2/router.go
routers/api/v2/router_test.go
routers/api/v2/tokens.go
routers/api/v2/tokens_test.go
routers/api/v2/types.go

Resolves #73 
This PR implements a route for auth v2 that generates an service token with the provided values of `expiresAt`, `allowedURIs` and `owner`.
We have discussed offline that the `allowedURIs` might not be needed in the JWT since those values will be stored in the DB which allows us to invalidate the service tokens more easily.

feat: Service token generation

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
authorization/v2/errors.go
authorization/v2/resources/resources.go
entities/user.go
routers/api/v2/router.go
routers/api/v2/router_test.go
routers/api/v2/types.go
routers/api/v2/users.go
routers/api/v2/users_test.go
services/mongo/userService.go
services/mongo/userService_test.go
services/userService.go

For issue #89 
Implements operations `GetUser` and `GetUsers` as described in the [specification](https://documenter.getpostman.com/view/2489646/T1DjjKP6?version=latest#59ac18d2-708b-430f-89f9-29e60f12c296).

feat: Implement GetUser and GetUsers for API v2

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
authorization/v2/types.go

Makes the `TokenClaims` struct used by the `Authorizer` private. `TokenClaims` stores the contents of v2 auth tokens. Logic for parsing, creating and extracting information from tokens should be localized to the `authorization/v2` package and as such `TokenClaims` should be a private struct.

chore: Make TokenClaims struct private

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
authorization/v2/types.go
routers/api/v2/router.go
routers/api/v2/router_test.go
routers/api/v2/teams.go
routers/api/v2/teams_test.go
routers/api/v2/tokens_test.go
routers/api/v2/types.go
routers/api/v2/users_test.go
wire_gen.go

For issue #84 
Implements the operations `GetTeams` `GetTeam` and `CreateTeam` as described in the [specification](https://documenter.getpostman.com/view/2489646/T1DjjKP6?version=latest#70577f61-4df6-4aa3-9b54-4be7e685ba6c).

feat: Implement teams API v2

---

.github/workflows/release.yml

Resolves #98 
Whenever a release is published, a new docker image is built and published to [Docker Hub](https://hub.docker.com/repository/docker/unicsmcr/hs_auth)

feat: on-release publish docker image

---

services/mongo/teamService.go
services/mongo/teamService_test.go

For issue #61 
Changes the `TeamService` behaviour when removing a team's creator from their team to not automatically delete the team. With this change the team will only be deleted if after removing the team's creator, the team will be empty. Otherwise, it assigns a new creator to the team from the existing members.

fix: Team deleted when creator leaves

---

routers/api/v2/users.go
routers/api/v2/users_test.go

Closes #68 
Updates the behaviour of `GetUsers` to return a `404` when the team specified by the `team` filter is not found.

fix: 200 returned for non-existant teams

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
authorization/v2/common/uniformResourceIdentifier.go
authorization/v2/common/uniformResourceIdentifier_test.go
authorization/v2/metadata.go
authorization/v2/metadata_test.go

For issue #92 
Updates the `Authorizer.GetAuthorizedResources` function to validate the metadata in the URIs. Also implements and example metadata validator.

feat: Implement URI metadata validation

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
config/base.yaml
config/config.go
config/development.yaml
routers/api/v1/users.go
routers/api/v1/users_test.go
routers/api/v2/router.go
routers/api/v2/router_test.go
routers/api/v2/users.go
routers/api/v2/users_test.go
routers/frontend/routes.go
routers/frontend/routes_test.go
services/emailServiceV2.go
services/mongo/userService.go
services/mongo/userService_test.go
services/sendgrid/emailService.go
services/sendgrid/emailService_test.go
services/sendgrid/v2/emailService.go
services/sendgrid/v2/emailService_test.go
services/userService.go
wire.go
wire_gen.go

Resolves #87 and #107 
Implements operations `VerifyEmail`, `ResendEmailVerification` and updates the `Register` operation to send an email verification email if email verification is enabled. Also implements an email service client that uses auth system v2 `EmailServiceV2`.
Sending an email when resetting the user's password has been temporarily disabled, it will be re-enabled in a separate PR which implements sending a password reset email through `EmailServiceV2`

feat: Implement email verification for API v2

---

.travis.yml
Makefile
authorization/v2/authorizer_test.go
routers/api/v2/users_test.go
testutils/testDB.go

Resolves #101 
The TravisCI `PR` build will fail for this PR, all following PRs will work as expected.
This PR adds performance tests to some of the most common/important routes in the v2 API. It also uses [cob](https://github.com/knqyf263/cob) to compare the performance of `HEAD` and `HEAD~1` commits.
Below is a list of the endpoints that have benchmarks implemented:
_Note:_ The benchmark results reported by cob will be different than results we see locally, the CI machines are probably much more powerful than local machines.

feat: Performance tests API v2

---

authorization/v2/authorizer.go
authorization/v2/authorizer_test.go
routers/api/v2/users.go
routers/api/v2/users_test.go
services/sendgrid/v2/emailService.go
services/sendgrid/v2/emailService_test.go

For issue #118 
Updates the `GetPasswordResetEmail` to use `EmailServiceV2` to send out the password reset email.

feat: Update GetPasswordResetEmail to use EmailService V2

---

go.mod
go.sum
routers/api/v2/router.go
routers/api/v2/router_test.go
routers/api/v2/users.go
routers/common/common.go
routers/common/common_test.go
routers/frontend/router.go
routers/frontend/router_test.go
routers/frontend/routes.go
routers/frontend/routes_test.go
wire_gen.go

For issue #106 
Migrates the frontend operation `Register` to use auth system v2.
Also resolves the following TODOs:
- https://github.com/unicsmcr/hs_auth/blob/master/routers/api/v2/users.go#L632
- https://github.com/unicsmcr/hs_auth/blob/master/routers/api/v2/users.go#L622

 feat: Migrate frontend Register to auth V2

---

routers/frontend/router.go
routers/frontend/routes.go
routers/frontend/routes_test.go

Resolves #144 
Moves the profile page to `/profile` and implements a handler for `/` to redirect the user to either `/login` or `/profile`.

feat: Move profile page to /profile

---

routers/frontend/routes.go
templates/partials/navbar.gohtml

I noticed while testing that the navbar component "return to previous location" gets displayed even when the `ReturnTo` cookie is invalid.
This PR updates the template for the "return to previous location" to render the component only if the `ReturnTo` cookie is not empty.

fix: ReturnTo in navbar displayed when ReturnTo cookie is invalid

---

templates/emails/emailVerify_email.gohtml
templates/emails/passwordReset_email.gohtml

This PR fixes the email templates to render the links as actual hyperlinks rather than plaintext.
Also updates the year in the emails to 2020.

fix: Links in emails are rendered as plaintext

---

config/role/role.yaml

This PR defines the resources required by hs_discord, and also configures the various roles in role.yaml with the correct hs_discord resources.
-----
These resources declare the 4 roles that users can be assigned in the Discord server. They should not be used by hs_discord to derive a user's permissions to perform an action. The associated Discord roles will have permissions, e.g. organisers will be able to post in the announcements channel. The attendee role on the other hand is purely decorative.
- `hs:hs_discord:guild:organiser`
- `hs:hs_discord:guild:volunteer`
- `hs:hs_discord:guild:sponsor`
- `hs:hs_discord:guild:attendee`
- `hs:hs_discord:bot:id` - permits access to the `!id` command on the Discord server
- `hs:hs_discord:bot:whois` - permits access to the `!whois` command to match …

Add hs_discord resources to role config

---

routers/api/v2/tokens.go
routers/api/v2/tokens_test.go

Updates the `GetAuthorizedResources` operations to return an empty array instead of null when none of the requested resources are authorized.

fix: Replace null response from GetAuthorizedResources with empty array
